### ISSUE TITLE
Declaración de la situación problema

### ISSUE THREAD

**Issue by Alejo-png** [Alejo-png/Equipo2_FO_PPI2020#4]

**Comment by Mateo-nor** [comment]
SITUACIÓN PROBLEMA

si hemos presenciado o nos hemos vuelto involucrados en tipo de accidente podemos observar que hay un alto porcentaje de que la ambulancia se demore mas de lo que debería a causa del mal sistema de salud y hay personas que le gustaría actuar ya que el tiempo que tarda una ambulancia es irregular y la persona en ese rango de tiempo puede morir , lo que queremos conseguir con esta aplicación es impedir que esto ocurra.
