### ISSUE TITLE
Titulo del proyecto

### ISSUE THREAD

**Issue by Alejo-png** [Alejo-png/Equipo2_FO_PPI2020#9]
titulo....
resumen......
autores.......

**Comment by Mateo-nor** [comment]
SALUD Y BIENESTAR

==nuestra aplicación consiste en una aplicación móvil que se encargara de brindar apoyo a sus usuarios para que puedan actuar de buena manera a la persona que encuentra afectada , esta aplicación contara con diferentes secciones una para que las personas no entren en pánico y se puedan tranquilizar para evitar cometer errores por presión , luego la sección de categoría a la que desea acudir automovilística o de desastre natural , luego al entrar se encontrara con los métodos a los que usted no tiene la capacidad de atender y debe evitar a toda costa ayudando únicamente a la linea de emergencias después de descartar que este entre esos se procede a escoger el tipo de lesión de grado menor para que el usuario sepa que hacer paso a paso.


autores:

-Mateo Noreña Patiño
-Alejandro osorno tamayo
-valentinca palacios
-kevin hicapie perez
